//
//  TwDistrictDataModel.swift
//  FransiSRentalHouseProject
//
//  Created by Kuan on 2022/4/19.
//

import Foundation

enum Cities: String, CaseIterable {
    case taipei = "Taipei"
    case newTaipei = "新北市"
    case taoyuan = "Taoyuan"
    case taichung = "Taichung"
    case tainan = "Tainan"
    case kaohsiung = "Kaohsiung"
    case hsinchu = "Hsinchu County"
    case miaoli = "Miaoli County"
    case chanhua = "Chanhua County"
    case nantou = "Nantou County"
    case yunlin = "Yunlin County"
    case chiayi = "Chiayi County"
    case pingtung = "Pingtung County"
    case yilan = "Yilan County"
    case hualien = "Hualien County"
    case taitung = "Taitung County"
    case penghu = "Penghu County"
    case kinmen = "Kinmen County"
    case matsu = "Matsu County"
    case keelungCity = "Keelung City"
    case hsinchuCity = "Hsinchu City"
    case chiayiCity = "Chiayi City"
}

enum TaipeiDistrict: String, CaseIterable {
    case Songshan = "Songshan District"
    case Xinyi = "Xinyi District"
    case Daan = "Daan District"
    case Zhongshan = "Zhongshan District"
    case Zhongzheng = "Zhongzheng District"
    case Datong = "Datong District"
    case Wanhua = "Wanhua District"
    case Wenshan = "Wenshan District"
    case Nangang = "Nangang District"
    case Neihu = "Neihu District"
    case Shilin = "Shilin District"
    case Beitou = "Beitou District"
}

enum NewTaipeiDistrict: String, CaseIterable {
    case Banqiao = "Banqiao District"
    case Sanchong = "Sanchong District"
    case Zhonghe = "Zhonghe District"
    case Yonghe = "Yonghe District"
    case Xinzhuang = "Xinzhuang District"
    case Xindian = "Xindian District"
    case Tucheng = "Tucheng District"
    case Luzhou = "Luzhou District"
    case Xizhi = "Xizhi District"
    case Shulin = "Shulin District"
    case Danshui = "Danshui District"
    case Yingge = "Yingge District"
    case Sanxia = "Sanxia District"
    case Ruifang = "Ruifang District"
    case Wugu = "Wugu District"
    case Linkou = "Linkou District"
    case Shenkeng = "Shenkeng District"
    case Shiding = "Shiding District"
    case Pinglin = "Pinglin District"
    case Sanzhi = "Sanzhi District"
    case Shimen = "Shimen District"
    case Bali = "Bali District"
    case Pingxi = "Pingxi District"
    case Shuangxi = "Shuangxi District"
    case Gongliao = "Gongliao District"
    case Jinshan = "Jinshan District"
    case Wanli = "Wanli District"
    case Wulai = "Wulai District"
}

enum TaoyuanDistrict: String, CaseIterable {
    case Zhongli = "Banqiao District"
    case Daxi = "Sanchong District"
    case Yangmei = "Zhonghe District"
    case Luzhu = "Yonghe District"
    case Dayuan = "Xinzhuang District"
    case Guishan = "Xindian District"
    case Bade = "Tucheng District"
    case Longtan = "Luzhou District"
    case Pingzhen = "Xizhi District"
    case Xinwu = "Shulin District"
    case Guanyin = "Danshui District"
}


enum TaichungDistrict: String, CaseIterable {
    case Central = "Central District"
    case East = "East District"
    case South = "South District"
    case West = "West District"
    case North = "North District"
    case Xitun = "Xitun District"
    case Nantun = "Nantun District"
    case Beitun = "Beitun District"
    case Fengyuan = "Fengyuan District"
    case Dongshi = "Dongshi District"
    case Dajia = "Dajia District"
    case Qingshui = "Qingshui District"
    case Shalu = "Shalu District"
    case Wuqi = "Wuqi District"
    case Houli = "Houli District"
    case Shengang = "Shengang District"
    case Tanzi = "Tanzi District"
    case Daya = "Daya District"
    case Xinshe = "Xinshe District"
    case Shigang = "Shigang District"
    case Waipu = "Waipu District"
    case Daan = "Daan District"
    case Wuri = "Wuri District"
    case Dadu = "Dadu District"
    case Longjing = "Longjing District"
    case Wufeng = "Wufeng District"
    case Taiping = "Taiping District"
    case Dali = "Dali District"
    case Heping = "Heping District"
}

enum TainanDistrict: String, CaseIterable {
    case Xinying = "Xinying District"
    case Yanshui = "Yanshui District"
    case Baihe = "Baihe District"
    case Liuying = "Liuying District"
    case Houbi = "Houbi District"
    case Dongshan = "Dongshan District"
    case Madou = "Madou District"
    case Xiaying = "Xiaying District"
    case Liujia = "Liujia District"
    case Guantian = "Guantian District"
    case Danei = "Danei District"
    case Jiali = "Jiali District"
    case Xuejia = "Xuejia District"
    case Xigang = "Xigang District"
    case Qigu = "Qigu District"
    case Jiangjun = "Jiangjun District"
    case Beimen = "Beimen District"
    case Xinhua = "Xinhua District"
    case Shanhua = "Shanhua District"
    case Xinshi = "Xinshi District"
    case Anding = "Anding District"
    case Shanshang = "Shanshang District"
    case Yujing = "Yujing District"
    case Nanxi = "Nanxi District"
    case Nanhua = "Nanhua District"
    case Zuozhen = "Zuozhen District"
    case Rende = "Rende District"
    case Guiren = "Guiren District"
    case Guanmiao = "Guanmiao District"
    case Longqi = "Longqi District"
    case Yongkang = "Yongkang District"
    case East = "East District"
    case North = "North District"
    case Annan = "Annan District"
    case Anping = "Anping District"
    case WestCentral = "WestCentral District"
}

enum KaohsiungDistrict: String, CaseIterable {
    case Yancheng = "Yancheng District"
    case Gushan = "Gushan District"
    case Zuoying = "Zuoying District"
    case Nanzi = "Nanzi District"
    case Sanmin = "Sanmin District"
    case Xinxing = "Xinxing District"
    case Qianjin = "Qianjin District"
    case Lingya = "Lingya District"
    case Qianzhen = "Qianzhen District"
    case Qijin = "Qijin District"
    case Xiaogang = "Xiaogang District"
    case Fengshan = "Fengshan District"
    case Linyuan = "Linyuan District"
    case Daliao = "Daliao District"
    case Dashu = "Dashu District"
    case Dashe = "Dashe District"
    case Renwu = "Renwu District"
    case Niaosong = "Niaosong District"
    case Gangshan = "Gangshan District"
    case Qiaotou = "Qiaotou District"
    case Yanchao = "Yanchao District"
    case Tianliao = "Tianliao District"
    case Alian = "Alian District"
    case Luzhu = "Luzhu District"
    case Hunei = "Hunei District"
    case Qieding = "Qieding District"
    case Yongan = "Yongan District"
    case Mituo = "Mituo District"
    case Ziguan = "Ziguan District"
    case Qishan = "Qishan District"
    case Meinong = "Meinong District"
    case Liugui = "Liugui District"
    case Jiaxian = "Jiaxian District"
    case Shanlin = "Shanlin District"
    case Neimen = "Neimen District"
    case Maolin = "Maolin District"
    case Taoyuan = "Taoyuan District"
    case Namaxia = "Namaxia District"
}

enum YilanDistrict: String, CaseIterable {
    case Luodong = "Luodong Township"
    case Suao = "Suao Township"
    case Toucheng = "Toucheng Township"
    case Jiaoxi = "Jiaoxi Township"
    case Zhuangwei = "Zhuangwei Township"
    case Yuanshan = "Yuanshan Township"
    case Dongshan = "Dongshan Township"
    case Wujie = "Wujie Township"
    case Sanxing = "Sanxing Township"
    case Datong = "Datong Township"
    case Nanao = "Nanao Township"
}


enum HsinchuDistrict: String, CaseIterable {
    case Zhubei = "Zhubei City"
    case Zhudong = "Zhudong Township"
    case Xinpu = "Xinpu Township"
    case Hukou = "Hukou Township"
    case Xinfeng = "Xinfeng Township"
    case Qionglin = "Qionglin Township"
    case Hengshan = "Hengshan Township"
    case Beipu = "Beipu Township"
    case Baoshan = "Baoshan Township"
    case Guanxi = "Guanxi Township"
    case Emei = "Emei Township"
    case Jianshi = "Jianshi Township"
    case Wufeng = "Wufeng Township"
}


enum MiaoliDistrict: String, CaseIterable {
    case Miaoli = "Miaoli City"
    case Yuanli = "Yuanli Township"
    case Tongxiao = "Tongxiao Township"
    case Zhunan = "Zhunan Township"
    case Toufen = "Toufen Township"
    case Houlong = "Houlong Township"
    case Zhuolan = "Zhuolan Township"
    case Dahu = "Dahu Township"
    case Gongguan = "Gongguan Township"
    case Tongluo = "Tongluo Township"
    case Nanzhuang = "Nanzhuang Township"
    case Touwu = "Touwu Township"
    case Sanyi = "Sanyi Township"
    case Xihu = "Xihu Township"
    case Zaoqiao = "Zaoqiao Township"
    case Sanwan = "Sanwan Township"
    case Shitan = "Shitan Township"
    case Taian = "Taian Township"
}

enum ChanghuaDistrict: String, CaseIterable {
    case Changhua = "Changhua City"
    case Yuanli = "Yuanli Township"
    case Tongxiao = "Tongxiao Township"
    case Zhunan = "Zhunan Township"
    case Toufen = "Toufen Township"
    case Houlong = "Houlong Township"
    case Zhuolan = "Zhuolan Township"
    case Dahu = "Dahu Township"
    case Gongguan = "Gongguan Township"
    case Tongluo = "Tongluo Township"
    case Nanzhuang = "Nanzhuang Township"
    case Touwu = "Touwu Township"
    case Sanyi = "Sanyi Township"
    case Xihu = "Xihu Township"
    case Zaoqiao = "Zaoqiao Township"
    case Sanwan = "Sanwan Township"
    case Shitan = "Shitan Township"
    case Taian = "Taian Township"
}

enum NantouDistrict: String, CaseIterable {
    case Nantou = "Nantou City"
    case Puli = "Puli Township"
    case Caotun = "Caotun Township"
    case Zhushan = "Zhushan Township"
    case Jiji = "Jiji Township"
    case Mingjian = "Mingjian Township"
    case Lugu = "Lugu Township"
    case Zhongliao = "Zhongliao Township"
    case Yuchi = "Yuchi Township"
    case Guoxing = "Guoxing Township"
    case Shuili = "Shuili Township"
    case Xinyi = "Xinyi Township"
    case Renai = "Renai Township"
}

enum YunlinDistrict: String, CaseIterable {
    case Douliu = "Douliu City"
    case Dounan = "Dounan Township"
    case Huwei = "Huwei Township"
    case Xiluo = "Xiluo Township"
    case Tuku = "Tuku Township"
    case Beigang = "Beigang Township"
    case Gukeng = "Gukeng Township"
    case Dapi = "Dapi Township"
    case Citong = "Citong Township"
    case Linnei = "Linnei Township"
    case Erlun = "Erlun Township"
    case Lunbei = "Lunbei Township"
    case Mailiao = "Mailiao Township"
    case Dongshi = "Dongshi City"
    case Baozhong = "Baozhong Township"
    case Taixi = "Taixi Township"
    case Yuanchang = "Yuanchang Township"
    case Sihu = "Sihu Township"
    case Shuilin = "Shuilin Township"
}

enum ChiayiDistrict: String, CaseIterable {
    case Taibao = "Taibao City"
    case Puzi = "Puzi City"
    case Budai = "Budai Township"
    case Dalin = "Dalin Township"
    case Minxiong = "Minxiong Township"
    case Xikou = "Xikou Township"
    case Xingang = "Xingang Township"
    case Liujiao = "Liujiao Township"
    case Dongshi = "Dongshi Township"
    case Yizhu = "Yizhu Township"
    case Lucao = "Lucao Township"
    case Shuishang = "Shuishang Township"
    case Zhongpu = "Zhongpu Township"
    case Zhuqi = "Zhuqi City"
    case Meishan = "Meishan Township"
    case Fanlu = "Fanlu Township"
    case Dapu = "Dapu Township"
    case Alishan = "Alishan Township"
}

enum PingtungDistrict: String, CaseIterable {
    case Pingtung = "Pingtung City"
    case Chaozhou = "Puzi City"
    case Donggang = "Donggang Township"
    case Hengchun = "Hengchun Township"
    case Wandan = "Wandan Township"
    case Changzhi = "Changzhi Township"
    case Linluo = "Linluo Township"
    case Jiuru = "Jiuru Township"
    case Ligang = "Ligang Township"
    case Yanpu = "Yanpu Township"
    case Gaoshu = "Gaoshu Township"
    case Wanluan = "Wanluan Township"
    case Neipu = "Neipu Township"
    case Zhutian = "Zhutian City"
    case Xinpi = "Xinpi Township"
    case Fangliao = "Fangliao Township"
    case Xinyuan = "Xinyuan Township"
    case Kanding = "Kanding Township"
    case Linbian = "Linbian Township"
    case Nanzhou = "Nanzhou Township"
    case Jiadong = "Jiadong Township"
    case Liuqiu = "Liuqiu Township"
    case Checheng = "Checheng Township"
    case Manzhou = "Manzhou Township"
    case Fangshan = "Fangshan Township"
    case Sandimen = "Sandimen Township"
    case Wutai = "Wutai Township"
    case Majia = "Majia Township"
    case Taiwu = "Taiwu Township"
    case LaiyiTownship = "LaiyiTownship City"
    case Chunri = "Chunri Township"
    case Shizi = "Shizi Township"
    case Mudan = "Mudan Township"
}

enum TaitungDistrict: String, CaseIterable {
    case Taitung = "Taitung City"
    case Chenggong = "Chenggong Township"
    case Guanshan = "Guanshan Township"
    case Beinan = "Beinan Township"
    case Luye = "Luye Township"
    case Chishang = "Chishang Township"
    case Donghe = "Donghe Township"
    case Changbin = "Changbin Township"
    case Taimali = "Taimali Township"
    case Dawu = "Dawu Township"
    case Lüdao = "Lüdao Township"
    case Haiduan = "Haiduan Township"
    case Yanping = "Yanping City"
    case Jinfeng = "Jinfeng Township"
    case Daren = "Daren Township"
    case Lanyu = "Lanyu Township"
}

enum HualienDistrict: String, CaseIterable {
    case Hualien = "Hualien City"
    case Yuli = "Yuli Township"
    case Xincheng = "Xincheng Township"
    case Jian = "Jian Township"
    case Shoufeng = "Shoufeng Township"
    case Guangfu = "Guangfu Township"
    case Fengbin = "Fengbin Township"
    case Ruisui = "Ruisui Township"
    case Fuli = "Fuli Township"
    case Xiulin = "Xiulin Township"
    case Wanrong = "Wanrong Township"
    case Zhuoxi = "Zhuoxi Township"
}

enum PenghuDistrict: String, CaseIterable {
    case Magong = "Magong City"
    case Huxi = "Huxi Township"
    case Baisha = "Baisha Township"
    case Xiyu = "Xiyu Township"
    case Wangan = "Wangan Township"
    case Qimei = "Qimei Township"
}

enum KeelungDistrict: String, CaseIterable {
    case Zhongzheng = "Zhongzheng Township"
    case Qidu = "Qidu Township"
    case Nuannuan = "Nuannuan Township"
    case Renai = "Renai Township"
    case Zhongshan = "Zhongshan Township"
    case Anle = "Anle Township"
    case Xinyi = "Xinyi Township"
}

enum HsinchuCity: String, CaseIterable {
    case East = "East Township"
    case North = "North Township"
    case Xiangshan = "Xiangshan Township"
}

enum ChiayiCity: String, CaseIterable {
    case East = "East Township"
    case West = "West Township"
}

enum MatsuDistrict: String, CaseIterable {
    case Nangan = "Nangan Township"
    case Beigan = "Beigan Township"
    case Juguang = "Juguang Township"
    case Dongyin = "Dongyin Township"
}

enum KinmenDistrict: String, CaseIterable {
    case Jincheng = "Jincheng Township"
    case Jinhu = "Jinhu Township"
    case Jinsha = "Jinsha Township"
    case Jinning = "Jinning Township"
    case Lieyu = "Lieyu Township"
    case Wuqiu = "Wuqiu Township"
}
