//
//  TwDistrictDataModel.swift
//  FransiSRentalHouseProject
//
//  Created by Kuan on 2022/4/19.
//

import Foundation

enum Cities: String, CaseIterable {
    case taipei = "臺北市"
    case newTaipei = "新北市"
    case taoyuan = "桃園市"
    case taichung = "臺中市"
    case tainan = "臺南市"
    case kaohsiung = "高雄市"
    case hsinchu = "新竹縣"
    case miaoli = "苗栗縣"
    case chanhua = "彰化縣"
    case nantou = "南投縣"
    case yunlin = "雲林縣"
    case chiayi = "嘉義縣"
    case pingtung = "屏東縣"
    case yilan = "宜蘭縣"
    case hualien = "花蓮縣"
    case taitung = "臺東縣"
    case penghu = "澎湖縣"
    case kinmen = "金門縣"
    case matsu = "連江縣"
    case keelungCity = "基隆市"
    case hsinchuCity = "新竹市"
    case chiayiCity = "嘉義市"
}

enum TaipeiDistrict: String, CaseIterable {
    case Songshan = "松山區"
    case Xinyi = "信義區"
    case Daan = "大安區"
    case Zhongshan = "中山區"
    case Zhongzheng = "中正區"
    case Datong = "大同區"
    case Wanhua = "萬華區"
    case Wenshan = "文山區"
    case Nangang = "南港區"
    case Neihu = "內湖區"
    case Shilin = "士林區"
    case Beitou = "北投區"
}

enum NewTaipeiDistrict: String, CaseIterable {
    case Banqiao = "板橋區"
    case Sanchong = "三重區"
    case Zhonghe = "中和區"
    case Yonghe = "永和區"
    case Xinzhuang = "新莊區"
    case Xindian = "新店區"
    case Tucheng = "土城區"
    case Luzhou = "蘆洲區"
    case Xizhi = "汐止區"
    case Shulin = "樹林區"
    case Danshui = "淡水區"
    case Yingge = "鶯歌區"
    case Sanxia = "三峽區"
    case Ruifang = "瑞芳區"
    case Wugu = "五股區"
    case Taishan = "泰山區"
    case Linkou = "林口區"
    case Shenkeng = "深坑區"
    case Shiding = "石碇區"
    case Pinglin = "坪林區"
    case Sanzhi = "三芝區"
    case Shimen = "石門區"
    case Bali = "八里區"
    case Pingxi = "帄溪區"
    case Shuangxi = "雙溪區"
    case Gongliao = "貢寮區"
    case Jinshan = "金山區"
    case Wanli = "萬里區"
    case Wulai = "烏來區"
}

enum TaoyuanDistrict: String, CaseIterable {
    case Taoyuan = "桃園區"
    case Zhongli = "中壢區"
    case Daxi = "大溪區"
    case Yangmei = "楊梅區"
    case Luzhu = "蘆竹區"
    case Dayuan = "大園區"
    case Guishan = "龜山區"
    case Bade = "八德區"
    case Longtan = "龍潭區"
    case Pingzhen = "帄鎮區"
    case Xinwu = "新屋區"
    case Guanyin = "觀音區"
    case Fuxing = "復興區"
}

enum TaichungDistrict: String, CaseIterable {
    case Central = "中區"
    case East = "東區"
    case South = "南區"
    case West = "西區"
    case North = "北區"
    case Xitun = "西屯區"
    case Nantun = "南屯區"
    case Beitun = "北屯區"
    case Fengyuan = "豐原區"
    case Dongshi = "東勢區"
    case Dajia = "大甲區"
    case Qingshui = "清水區"
    case Shalu = "沙鹿區"
    case Wuqi = "梧棲區"
    case Houli = "后里區"
    case Shengang = "神岡區"
    case Tanzi = "潭子區"
    case Daya = "大雅區"
    case Xinshe = "新社區"
    case Shigang = "石岡區"
    case Waipu = "外埔區"
    case Daan = "大安區"
    case Wuri = "烏日區"
    case Dadu = "大肚區"
    case Longjing = "龍井區"
    case Wufeng = "霧峰區"
    case Taiping = "太平區"
    case Dali = "大里區"
    case Heping = "和平區"
}


enum TainanDistrict: String, CaseIterable {
    case Xinying = "新營區"
    case Yanshui = "鹽水區"
    case Baihe = "白河區"
    case Liuying = "柳營區"
    case Houbi = "後壁區"
    case Dongshan = "東山區"
    case Madou = "麻豆區"
    case Xiaying = "下營區"
    case Liujia = "六甲區"
    case Guantian = "官田區"
    case Danei = "大內區"
    case Jiali = "佳里區"
    case Xuejia = "學甲區"
    case Xigang = "西港區"
    case Qigu = "七股區"
    case Jiangjun = "將軍區"
    case Beimen = "北門區"
    case Xinhua = "新化區"
    case Shanhua = "善化區"
    case Xinshi = "新市區"
    case Anding = "安定區"
    case Shanshang = "山上區"
    case Yujing = "玉井區"
    case Nanxi = "楠西區"
    case Nanhua = "南化區"
    case Zuozhen = "左鎮區"
    case Rende = "仁德區"
    case Guiren = "歸仁區"
    case Guanmiao = "關廟區"
    case Longqi = "龍崎區"
    case Yongkang = "永康區"
    case East = "東區"
    case South = "南區"
    case North = "北區"
    case Annan = "安南區"
    case Anping = "安平區"
    case WestCentral = "中西區"
}


enum KaohsiungDistrict: String, CaseIterable {
    case Yancheng = "鹽埕區"
    case Gushan = "鼓山區"
    case Zuoying = "左營區"
    case Nanzi = "楠梓區"
    case Sanmin = "三民區"
    case Xinxing = "新興區"
    case Qianjin = "前金區"
    case Lingya = "苓雅區"
    case Qianzhen = "前鎮區"
    case Qijin = "旗津區"
    case Xiaogang = "小港區"
    case Fengshan = "鳳山區"
    case Linyuan = "林園區"
    case Daliao = "大寮區"
    case Dashu = "大樹區"
    case Dashe = "大社區"
    case Renwu = "仁武區"
    case Niaosong = "鳥松區"
    case Gangshan = "岡山區"
    case Qiaotou = "橋頭區"
    case Yanchao = "燕巢區"
    case Tianliao = "田寮區"
    case Alian = "阿蓮區"
    case Luzhu = "路竹區"
    case Hunei = "湖內區"
    case Qieding = "茄萣區"
    case Yongan = "永安區"
    case Mituo = "彌陀區"
    case Ziguan = "梓官區"
    case Qishan = "旗山區"
    case Meinong = "美濃區"
    case Liugui = "六龜區"
    case Jiaxian = "甲仙區"
    case Shanlin = "杉林區"
    case Neimen = "內門區"
    case Maolin = "茂林區"
    case Taoyuan = "桃源區"
    case Namaxia = "那瑪夏區"
}

enum YilanDistrict: String, CaseIterable {
    case Yilan = "宜蘭市"
    case Luodong = "羅東鎮"
    case Suao = "蘇澳鎮"
    case Toucheng = "頭城鎮"
    case Jiaoxi = "礁溪鄉"
    case Zhuangwei = "壯圍鄉"
    case Yuanshan = "員山鄉"
    case Dongshan = "冬山鄉"
    case Wujie = "五結鄉"
    case Sanxing = "三星鄉"
    case Datong = "大同鄉"
    case Nanao = "南澳鄉"
}

enum HsinchuDistrict: String, CaseIterable {
    case Zhubei = "竹北市"
    case Zhudong = "竹東鎮"
    case Xinpu = "新埔鎮"
    case Hukou = "湖口鄉"
    case Xinfeng = "新豐鄉"
    case Qionglin = "芎林鄉"
    case Hengshan = "橫山鄉"
    case Beipu = "北埔鄉"
    case Baoshan = "寶山鄉"
    case Guanxi = "關西鎮"
    case Emei = "峨眉鄉"
    case Jianshi = "尖石鄉"
    case Wufeng = "五峰鄉"
}

enum MiaoliDistrict: String, CaseIterable {
    case Miaoli = "苗栗市"
    case Yuanli = "苑裡鎮"
    case Tongxiao = "通霄鎮"
    case Zhunan = "竹南鎮"
    case Toufen = "頭份鎮"
    case Houlong = "後龍鎮"
    case Zhuolan = "卓蘭鎮"
    case Dahu = "大湖鄉"
    case Gongguan = "公館鄉"
    case Tongluo = "銅鑼鄉"
    case Nanzhuang = "南庄鄉"
    case Touwu = "頭屋鄉"
    case Sanyi = "三義鄉"
    case Xihu = "西湖鄉"
    case Zaoqiao = "造橋鄉"
    case Sanwan = "三灣鄉"
    case Shitan = "獅潭鄉"
    case Taian = "泰安鄉"
}


enum ChanghuaDistrict: String, CaseIterable {
    case Changhua = "彰化市"
    case Lugang = "鹿港鎮"
    case Hemei = "和美鎮"
    case Xianxi = "線西鄉"
    case Shengang = "伸港鄉"
    case Fuxing = "福興鄉"
    case Xiushui = "秀水鄉"
    case Huatan = "花壇鄉"
    case Fenyuan = "芬園鄉"
    case Yuanlin = "員林鎮"
    case Xihu = "溪湖鎮"
    case Tianzhong = "田中鎮"
    case Dacun = "大村鄉"
    case Puyan = "埔鹽鄉"
    case Puxin = "埔心鄉"
    case Yongjing = "永靖鄉"
    case Shetou = "社頭鄉"
    case Ershui = "二水鄉"
    case Beidou = "北斗鎮"
    case Erlin = "二林鎮"
    case Tianwei = "田尾鄉"
    case Pitou = "埤頭鄉"
    case Fangyuan = "芳苑鄉"
    case Dacheng = "大城鄉"
    case Zhutang = "竹塘鄉"
    case Xizhou = "溪州鄉"
}

enum NantouDistrict: String, CaseIterable {
    case Nantou = "南投市"
    case Puli = "埔里鎮"
    case Caotun = "草屯鎮"
    case Zhushan = "竹山鎮"
    case Jiji = "集集鎮"
    case Mingjian = "名間鄉"
    case Lugu = "鹿谷鄉"
    case Zhongliao = "中寮鄉"
    case Yuchi = "魚池鄉"
    case Guoxing = "國姓鄉"
    case Shuili = "水里鄉"
    case Xinyi = "信義鄉"
    case Renai = "仁愛鄉"
}

enum YunlinDistrict: String, CaseIterable {
    case Douliu = "斗六市"
    case Dounan = "斗南鎮"
    case Huwei = "虎尾鎮"
    case Xiluo = "西螺鎮"
    case Tuku = "土庫鎮"
    case Beigang = "北港鎮"
    case Gukeng = "古坑鄉"
    case Dapi = "大埤鄉"
    case Citong = "莿桐鄉"
    case Linnei = "林內鄉"
    case Erlun = "二崙鄉"
    case Lunbei = "崙背鄉"
    case Mailiao = "麥寮鄉"
    case Dongshi = "東勢鄉"
    case Baozhong = "褒忠鄉"
    case Taixi = "臺西鄉"
    case Yuanchang = "元長鄉"
    case Sihu = "四湖鄉"
    case Kouhu = "口湖鄉"
    case Shuilin = "水林鄉"
}

enum ChiayiDistrict: String, CaseIterable {
    case Taibao = "太保市"
    case Puzi = "朴子市"
    case Budai = "布袋鎮"
    case Dalin = "大林鎮"
    case Minxiong = "民雄鄉"
    case Xikou = "溪口鄉"
    case Xingang = "新港鄉"
    case Liujiao = "六腳鄉"
    case Dongshi = "東石鄉"
    case Yizhu = "義竹鄉"
    case Lucao = "鹿草鄉"
    case Shuishang = "水上鄉"
    case Zhongpu = "中埔鄉"
    case Zhuqi = "竹崎鄉"
    case Meishan = "梅山鄉"
    case Fanlu = "番路鄉"
    case Dapu = "大埔鄉"
    case Alishan = "阿里山鄉"
}


enum PingtungDistrict: String, CaseIterable {
    case Pingtung = "屏東市"
    case Chaozhou = "潮州鎮"
    case Donggang = "東港鎮"
    case Hengchun = "恆春鎮"
    case Wandan = "萬丹鄉"
    case Changzhi = "長治鄉"
    case Linluo = "麟洛鄉"
    case Jiuru = "九如鄉"
    case Ligang = "里港鄉"
    case Yanpu = "鹽埔鄉"
    case Gaoshu = "高樹鄉"
    case Wanluan = "萬巒鄉"
    case Neipu = "內埔鄉"
    case Zhutian = "竹田鄉"
    case Xinpi = "新埤鄉"
    case Fangliao = "枋寮鄉"
    case Xinyuan = "新園鄉"
    case Kanding = "崁頂鄉"
    case Linbian = "林邊鄉"
    case Nanzhou = "南州鄉"
    case Jiadong = "佳冬鄉"
    case Liuqiu = "琉球鄉"
    case Checheng = "車城鄉"
    case Manzhou = "滿州鄉"
    case Fangshan = "枋山鄉"
    case Sandimen = "三地門鄉"
    case Wutai = "霧臺鄉"
    case Majia = "瑪家鄉"
    case Taiwu = "泰武鄉"
    case Laiyi = "來義鄉"
    case Chunri = "春日鄉"
    case Shizi = "獅子鄉"
    case Mudan = "牡丹鄉"
}
                              

enum TaitungDistrict: String, CaseIterable {
    case Taitung = "臺東市"
    case Chenggong = "成功鎮"
    case Guanshan = "關山鎮"
    case Beinan = "卑南鄉"
    case Luye = "鹿野鄉"
    case Chishang = "池上鄉"
    case Donghe = "東河鄉"
    case Changbin = "長濱鄉"
    case Taimali = "太麻里鄉"
    case Dawu = "大武鄉"
    case Lüdao = "綠島鄉"
    case Haiduan = "海端鄉"
    case Yanping = "延帄鄉"
    case Jinfeng = "金峰鄉"
    case Daren = "達仁鄉"
    case Lanyu = "蘭嶼鄉"
}
             

enum HualienDistrict: String, CaseIterable {
    case Hualien = "花蓮市"
    case Fenglin = "鳳林鎮"
    case Yuli = "玉里鎮"
    case Xincheng = "新城鄉"
    case Jian = "吉安鄉"
    case Shoufeng = "壽豐鄉"
    case Guangfu = "光復鄉"
    case Fengbin = "豐濱鄉"
    case Ruisui = "瑞穗鄉"
    case Fuli = "富里鄉"
    case Xiulin = "秀林鄉"
    case Wanrong = "萬榮鄉"
    case Zhuoxi = "卓溪鄉"
}
          

enum PenghuDistrict: String, CaseIterable {
    case Magong = "馬公市"
    case Huxi = "湖西鄉"
    case Baisha = "白沙鄉"
    case Xiyu = "西嶼鄉"
    case Wangan = "望安鄉"
    case Qimei = "七美鄉"
}

enum KeelungDistrict: String, CaseIterable {
    case Zhongzheng = "中正區"
    case Qidu = "七堵區"
    case Nuannuan = "暖暖區"
    case Renai = "仁愛區"
    case Zhongshan = "中山區"
    case Anle = "安樂區"
    case Xinyi = "信義區"
}

enum HsinchuCity: String, CaseIterable {
    case East = "東區"
    case North = "北區"
    case Xiangshan = "香山區"
}

enum ChiayiCity: String, CaseIterable {
    case East = "東區"
    case West = "西區"
}

enum MatsuDistrict: String, CaseIterable {
    case Nangan = "南竿鄉"
    case Beigan = "北竿鄉"
    case Juguang = "莒光鄉"
    case Dongyin = "東引鄉"
}


enum KinmenDistrict: String, CaseIterable {
    case Jincheng = "金城鎮"
    case Jinhu = "金湖鎮"
    case Jinsha = "金沙鎮"
    case Jinning = "金寧鄉"
    case Lieyu = "烈嶼鄉"
    case Wuqiu = "烏坵鄉"
}


/*

 enum Cities: String, CaseIterable {
     case taipei = "臺北市"
     case newTaipei = "新北市"
     case taoyuan = "Taoyuan"
     case taichung = "Taichung"
     case tainan = "Tainan"
     case kaohsiung = "Kaohsiung"
     case hsinchu = "Hsinchu County"
     case miaoli = "Miaoli County"
     case chanhua = "Chanhua County"
     case nantou = "Nantou County"
     case yunlin = "Yunlin County"
     case chiayi = "Chiayi County"
     case pingtung = "Pingtung County"
     case yilan = "Yilan County"
     case hualien = "Hualien County"
     case taitung = "Taitung County"
     case penghu = "Penghu County"
     case kinmen = "Kinmen County"
     case matsu = "Matsu County"
     case keelungCity = "Keelung City"
     case hsinchuCity = "Hsinchu City"
     case chiayiCity = "Chiayi City"
 }

 enum TaipeiDistrict: String, CaseIterable {
     case Songshan = "松山區"
     case Xinyi = "信義區"
     case Daan = "大安區"
     case Zhongshan = "中山區"
     case Zhongzheng = "中正區"
     case Datong = "大同區"
     case Wanhua = "萬華區"
     case Wenshan = "文山區"
     case Nangang = "南港區"
     case Neihu = "內湖區"
     case Shilin = "士林區"
     case Beitou = "北投區"
 }

 enum NewTaipeiDistrict: String, CaseIterable {
     case Banqiao = "Banqiao District"
     case Sanchong = "Sanchong District"
     case Zhonghe = "Zhonghe District"
     case Yonghe = "Yonghe District"
     case Xinzhuang = "Xinzhuang District"
     case Xindian = "Xindian District"
     case Tucheng = "Tucheng District"
     case Luzhou = "Luzhou District"
     case Xizhi = "Xizhi District"
     case Shulin = "Shulin District"
     case Danshui = "Danshui District"
     case Yingge = "Yingge District"
     case Sanxia = "Sanxia District"
     case Ruifang = "Ruifang District"
     case Wugu = "Wugu District"
     case Linkou = "Linkou District"
     case Shenkeng = "Shenkeng District"
     case Shiding = "Shiding District"
     case Pinglin = "Pinglin District"
     case Sanzhi = "Sanzhi District"
     case Shimen = "Shimen District"
     case Bali = "Bali District"
     case Pingxi = "Pingxi District"
     case Shuangxi = "Shuangxi District"
     case Gongliao = "Gongliao District"
     case Jinshan = "Jinshan District"
     case Wanli = "Wanli District"
     case Wulai = "Wulai District"
 }

 enum TaoyuanDistrict: String, CaseIterable {
     case Zhongli = "Banqiao District"
     case Daxi = "Sanchong District"
     case Yangmei = "Zhonghe District"
     case Luzhu = "Yonghe District"
     case Dayuan = "Xinzhuang District"
     case Guishan = "Xindian District"
     case Bade = "Tucheng District"
     case Longtan = "Luzhou District"
     case Pingzhen = "Xizhi District"
     case Xinwu = "Shulin District"
     case Guanyin = "Danshui District"
 }


 enum TaichungDistrict: String, CaseIterable {
     case Central = "Central District"
     case East = "East District"
     case South = "South District"
     case West = "West District"
     case North = "North District"
     case Xitun = "Xitun District"
     case Nantun = "Nantun District"
     case Beitun = "Beitun District"
     case Fengyuan = "Fengyuan District"
     case Dongshi = "Dongshi District"
     case Dajia = "Dajia District"
     case Qingshui = "Qingshui District"
     case Shalu = "Shalu District"
     case Wuqi = "Wuqi District"
     case Houli = "Houli District"
     case Shengang = "Shengang District"
     case Tanzi = "Tanzi District"
     case Daya = "Daya District"
     case Xinshe = "Xinshe District"
     case Shigang = "Shigang District"
     case Waipu = "Waipu District"
     case Daan = "Daan District"
     case Wuri = "Wuri District"
     case Dadu = "Dadu District"
     case Longjing = "Longjing District"
     case Wufeng = "Wufeng District"
     case Taiping = "Taiping District"
     case Dali = "Dali District"
     case Heping = "Heping District"
 }

 enum TainanDistrict: String, CaseIterable {
     case Xinying = "Xinying District"
     case Yanshui = "Yanshui District"
     case Baihe = "Baihe District"
     case Liuying = "Liuying District"
     case Houbi = "Houbi District"
     case Dongshan = "Dongshan District"
     case Madou = "Madou District"
     case Xiaying = "Xiaying District"
     case Liujia = "Liujia District"
     case Guantian = "Guantian District"
     case Danei = "Danei District"
     case Jiali = "Jiali District"
     case Xuejia = "Xuejia District"
     case Xigang = "Xigang District"
     case Qigu = "Qigu District"
     case Jiangjun = "Jiangjun District"
     case Beimen = "Beimen District"
     case Xinhua = "Xinhua District"
     case Shanhua = "Shanhua District"
     case Xinshi = "Xinshi District"
     case Anding = "Anding District"
     case Shanshang = "Shanshang District"
     case Yujing = "Yujing District"
     case Nanxi = "Nanxi District"
     case Nanhua = "Nanhua District"
     case Zuozhen = "Zuozhen District"
     case Rende = "Rende District"
     case Guiren = "Guiren District"
     case Guanmiao = "Guanmiao District"
     case Longqi = "Longqi District"
     case Yongkang = "Yongkang District"
     case East = "East District"
     case North = "North District"
     case Annan = "Annan District"
     case Anping = "Anping District"
     case WestCentral = "WestCentral District"
 }

 enum KaohsiungDistrict: String, CaseIterable {
     case Yancheng = "Yancheng District"
     case Gushan = "Gushan District"
     case Zuoying = "Zuoying District"
     case Nanzi = "Nanzi District"
     case Sanmin = "Sanmin District"
     case Xinxing = "Xinxing District"
     case Qianjin = "Qianjin District"
     case Lingya = "Lingya District"
     case Qianzhen = "Qianzhen District"
     case Qijin = "Qijin District"
     case Xiaogang = "Xiaogang District"
     case Fengshan = "Fengshan District"
     case Linyuan = "Linyuan District"
     case Daliao = "Daliao District"
     case Dashu = "Dashu District"
     case Dashe = "Dashe District"
     case Renwu = "Renwu District"
     case Niaosong = "Niaosong District"
     case Gangshan = "Gangshan District"
     case Qiaotou = "Qiaotou District"
     case Yanchao = "Yanchao District"
     case Tianliao = "Tianliao District"
     case Alian = "Alian District"
     case Luzhu = "Luzhu District"
     case Hunei = "Hunei District"
     case Qieding = "Qieding District"
     case Yongan = "Yongan District"
     case Mituo = "Mituo District"
     case Ziguan = "Ziguan District"
     case Qishan = "Qishan District"
     case Meinong = "Meinong District"
     case Liugui = "Liugui District"
     case Jiaxian = "Jiaxian District"
     case Shanlin = "Shanlin District"
     case Neimen = "Neimen District"
     case Maolin = "Maolin District"
     case Taoyuan = "Taoyuan District"
     case Namaxia = "Namaxia District"
 }

 enum YilanDistrict: String, CaseIterable {
     case Luodong = "Luodong Township"
     case Suao = "Suao Township"
     case Toucheng = "Toucheng Township"
     case Jiaoxi = "Jiaoxi Township"
     case Zhuangwei = "Zhuangwei Township"
     case Yuanshan = "Yuanshan Township"
     case Dongshan = "Dongshan Township"
     case Wujie = "Wujie Township"
     case Sanxing = "Sanxing Township"
     case Datong = "Datong Township"
     case Nanao = "Nanao Township"
 }


 enum HsinchuDistrict: String, CaseIterable {
     case Zhubei = "Zhubei City"
     case Zhudong = "Zhudong Township"
     case Xinpu = "Xinpu Township"
     case Hukou = "Hukou Township"
     case Xinfeng = "Xinfeng Township"
     case Qionglin = "Qionglin Township"
     case Hengshan = "Hengshan Township"
     case Beipu = "Beipu Township"
     case Baoshan = "Baoshan Township"
     case Guanxi = "Guanxi Township"
     case Emei = "Emei Township"
     case Jianshi = "Jianshi Township"
     case Wufeng = "Wufeng Township"
 }


 enum MiaoliDistrict: String, CaseIterable {
     case Miaoli = "Miaoli City"
     case Yuanli = "Yuanli Township"
     case Tongxiao = "Tongxiao Township"
     case Zhunan = "Zhunan Township"
     case Toufen = "Toufen Township"
     case Houlong = "Houlong Township"
     case Zhuolan = "Zhuolan Township"
     case Dahu = "Dahu Township"
     case Gongguan = "Gongguan Township"
     case Tongluo = "Tongluo Township"
     case Nanzhuang = "Nanzhuang Township"
     case Touwu = "Touwu Township"
     case Sanyi = "Sanyi Township"
     case Xihu = "Xihu Township"
     case Zaoqiao = "Zaoqiao Township"
     case Sanwan = "Sanwan Township"
     case Shitan = "Shitan Township"
     case Taian = "Taian Township"
 }

 enum ChanghuaDistrict: String, CaseIterable {
     case Changhua = "Changhua City"
     case Yuanli = "Yuanli Township"
     case Tongxiao = "Tongxiao Township"
     case Zhunan = "Zhunan Township"
     case Toufen = "Toufen Township"
     case Houlong = "Houlong Township"
     case Zhuolan = "Zhuolan Township"
     case Dahu = "Dahu Township"
     case Gongguan = "Gongguan Township"
     case Tongluo = "Tongluo Township"
     case Nanzhuang = "Nanzhuang Township"
     case Touwu = "Touwu Township"
     case Sanyi = "Sanyi Township"
     case Xihu = "Xihu Township"
     case Zaoqiao = "Zaoqiao Township"
     case Sanwan = "Sanwan Township"
     case Shitan = "Shitan Township"
     case Taian = "Taian Township"
 }

 enum NantouDistrict: String, CaseIterable {
     case Nantou = "Nantou City"
     case Puli = "Puli Township"
     case Caotun = "Caotun Township"
     case Zhushan = "Zhushan Township"
     case Jiji = "Jiji Township"
     case Mingjian = "Mingjian Township"
     case Lugu = "Lugu Township"
     case Zhongliao = "Zhongliao Township"
     case Yuchi = "Yuchi Township"
     case Guoxing = "Guoxing Township"
     case Shuili = "Shuili Township"
     case Xinyi = "Xinyi Township"
     case Renai = "Renai Township"
 }

 enum YunlinDistrict: String, CaseIterable {
     case Douliu = "Douliu City"
     case Dounan = "Dounan Township"
     case Huwei = "Huwei Township"
     case Xiluo = "Xiluo Township"
     case Tuku = "Tuku Township"
     case Beigang = "Beigang Township"
     case Gukeng = "Gukeng Township"
     case Dapi = "Dapi Township"
     case Citong = "Citong Township"
     case Linnei = "Linnei Township"
     case Erlun = "Erlun Township"
     case Lunbei = "Lunbei Township"
     case Mailiao = "Mailiao Township"
     case Dongshi = "Dongshi City"
     case Baozhong = "Baozhong Township"
     case Taixi = "Taixi Township"
     case Yuanchang = "Yuanchang Township"
     case Sihu = "Sihu Township"
     case Shuilin = "Shuilin Township"
 }

 enum ChiayiDistrict: String, CaseIterable {
     case Taibao = "Taibao City"
     case Puzi = "Puzi City"
     case Budai = "Budai Township"
     case Dalin = "Dalin Township"
     case Minxiong = "Minxiong Township"
     case Xikou = "Xikou Township"
     case Xingang = "Xingang Township"
     case Liujiao = "Liujiao Township"
     case Dongshi = "Dongshi Township"
     case Yizhu = "Yizhu Township"
     case Lucao = "Lucao Township"
     case Shuishang = "Shuishang Township"
     case Zhongpu = "Zhongpu Township"
     case Zhuqi = "Zhuqi City"
     case Meishan = "Meishan Township"
     case Fanlu = "Fanlu Township"
     case Dapu = "Dapu Township"
     case Alishan = "Alishan Township"
 }

 enum PingtungDistrict: String, CaseIterable {
     case Pingtung = "Pingtung City"
     case Chaozhou = "Puzi City"
     case Donggang = "Donggang Township"
     case Hengchun = "Hengchun Township"
     case Wandan = "Wandan Township"
     case Changzhi = "Changzhi Township"
     case Linluo = "Linluo Township"
     case Jiuru = "Jiuru Township"
     case Ligang = "Ligang Township"
     case Yanpu = "Yanpu Township"
     case Gaoshu = "Gaoshu Township"
     case Wanluan = "Wanluan Township"
     case Neipu = "Neipu Township"
     case Zhutian = "Zhutian City"
     case Xinpi = "Xinpi Township"
     case Fangliao = "Fangliao Township"
     case Xinyuan = "Xinyuan Township"
     case Kanding = "Kanding Township"
     case Linbian = "Linbian Township"
     case Nanzhou = "Nanzhou Township"
     case Jiadong = "Jiadong Township"
     case Liuqiu = "Liuqiu Township"
     case Checheng = "Checheng Township"
     case Manzhou = "Manzhou Township"
     case Fangshan = "Fangshan Township"
     case Sandimen = "Sandimen Township"
     case Wutai = "Wutai Township"
     case Majia = "Majia Township"
     case Taiwu = "Taiwu Township"
     case LaiyiTownship = "LaiyiTownship City"
     case Chunri = "Chunri Township"
     case Shizi = "Shizi Township"
     case Mudan = "Mudan Township"
 }

 enum TaitungDistrict: String, CaseIterable {
     case Taitung = "Taitung City"
     case Chenggong = "Chenggong Township"
     case Guanshan = "Guanshan Township"
     case Beinan = "Beinan Township"
     case Luye = "Luye Township"
     case Chishang = "Chishang Township"
     case Donghe = "Donghe Township"
     case Changbin = "Changbin Township"
     case Taimali = "Taimali Township"
     case Dawu = "Dawu Township"
     case Lüdao = "Lüdao Township"
     case Haiduan = "Haiduan Township"
     case Yanping = "Yanping City"
     case Jinfeng = "Jinfeng Township"
     case Daren = "Daren Township"
     case Lanyu = "Lanyu Township"
 }

 enum HualienDistrict: String, CaseIterable {
     case Hualien = "Hualien City"
     case Yuli = "Yuli Township"
     case Xincheng = "Xincheng Township"
     case Jian = "Jian Township"
     case Shoufeng = "Shoufeng Township"
     case Guangfu = "Guangfu Township"
     case Fengbin = "Fengbin Township"
     case Ruisui = "Ruisui Township"
     case Fuli = "Fuli Township"
     case Xiulin = "Xiulin Township"
     case Wanrong = "Wanrong Township"
     case Zhuoxi = "Zhuoxi Township"
 }

 enum PenghuDistrict: String, CaseIterable {
     case Magong = "Magong City"
     case Huxi = "Huxi Township"
     case Baisha = "Baisha Township"
     case Xiyu = "Xiyu Township"
     case Wangan = "Wangan Township"
     case Qimei = "Qimei Township"
 }

 enum KeelungDistrict: String, CaseIterable {
     case Zhongzheng = "Zhongzheng Township"
     case Qidu = "Qidu Township"
     case Nuannuan = "Nuannuan Township"
     case Renai = "Renai Township"
     case Zhongshan = "Zhongshan Township"
     case Anle = "Anle Township"
     case Xinyi = "Xinyi Township"
 }

 enum HsinchuCity: String, CaseIterable {
     case East = "East Township"
     case North = "North Township"
     case Xiangshan = "Xiangshan Township"
 }

 enum ChiayiCity: String, CaseIterable {
     case East = "East Township"
     case West = "West Township"
 }

 enum MatsuDistrict: String, CaseIterable {
     case Nangan = "Nangan Township"
     case Beigan = "Beigan Township"
     case Juguang = "Juguang Township"
     case Dongyin = "Dongyin Township"
 }

 enum KinmenDistrict: String, CaseIterable {
     case Jincheng = "Jincheng Township"
     case Jinhu = "Jinhu Township"
     case Jinsha = "Jinsha Township"
     case Jinning = "Jinning Township"
     case Lieyu = "Lieyu Township"
     case Wuqiu = "Wuqiu Township"
 }

*/
